# Generated by Django 3.0.8 on 2020-08-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='', null=True)),
                ('p_image', models.ImageField(upload_to='static/files/products')),
                ('volume_weight', models.CharField(default='', max_length=20)),
                ('buying_price', models.IntegerField(default=0, max_length=5)),
                ('available_quantity', models.IntegerField(default=0, max_length=3)),
                ('bar_code', models.CharField(default='', max_length=30)),
                ('bar_code_image', models.ImageField(upload_to='static/files/bar_codes')),
                ('selling_price', models.IntegerField(default=0, max_length=5)),
                ('brand', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Brand')),
                ('p_type', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductType')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
